#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

__dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

mkdir -p ${__dir}/../xml/source/

cp -f /Library/Application\ Support/Adobe/Scripting\ Dictionaries\ CC/CommonFiles/*.xml ${__dir}/../xml/source/
cp -f /Library/Application\ Support/Adobe/Scripting\ Dictionaries\ CC/Illustrator*/omv.xml ${__dir}/../xml/source/illustrator.xml
cp -f /Library/Application\ Support/Adobe/Scripting\ Dictionaries\ CC/photoshop/omv.xml ${__dir}/../xml/source/photoshop.xml
if [ -f "~/Library/Preferences/ExtendScript\ Toolkit/4.0/omv*.xml" ]; then
    cp -f ~/Library/Preferences/ExtendScript\ Toolkit/4.0/omv*.xml ${__dir}/../xml/source/
fi

exit 0

